version: "3"
services:
  auth:
    image: keycloak-workshop/keycloak:latest
    ports:
      - "443:443"
      - "8100:8100"
      - "8443:8443"
      - "8463:8463"
      - "8787:8787"
    environment:
      KEYCLOAK_USER: onwelo
      KEYCLOAK_PASSWORD: workshop
